---
# Source: knative-stack/templates/knative-eventing.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-eventing
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/paoloyx/istio-knative
    targetRevision: HEAD
    path: components/knative-eventing
  destination:
    server: https://kubernetes.default.svc
    namespace: knative-eventing
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jsonPointers:
        - /rules
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
---
# Source: knative-stack/templates/knative-operator.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/paoloyx/istio-knative
    targetRevision: HEAD
    path: components/knative-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: knative
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jsonPointers:
        - /rules
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
---
# Source: knative-stack/templates/knative-serving.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-serving
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/paoloyx/istio-knative
    targetRevision: HEAD
    path: components/knative-serving
  destination:
    server: https://kubernetes.default.svc
    namespace: knative-serving
  ignoreDifferences:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
      jsonPointers:
        - /rules
    - group: admissionregistration.k8s.io/v1
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks
    - group: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
